### ISSUE TITLE
Unable to add multiple configurations for spring cloud load balancer with SimpleDiscoveryClient 

### ISSUE THREAD

**Issue by neelimaj97** [spring-cloud/spring-cloud-commons#1016]
I want to use health-check and same-instance-preference configurations for spring cloud load balancer at the same time. Unable to give mutiple configuration. I tried with yml configuration and configuration bean definition also.
I am using SimpleDiscoveryClient for listing out the instances. Additionally, if both these configurations are clubbed, can it be a replacement for sticky session loadbalancer rule?

Posting my yml here:
````
spring:
  application:
    name: sample
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false
        simple:
          instances:
            test-service:
              - uri: http://localhost:8082
              - uri: http://localhost:8081
    loadbalancer:
#      configurations: health-check
      configurations: same-instance-preference
      sticky-session:
        add-service-instance-cookie: true
      cache:
        enabled: false
      health-check:
        path:
          default: /actuator/health
        interval: 10000
    gateway:
      routes:
        - id: test_routing
          path: /user/*
          uri: lb://test-service
          predicates:
            - Method=GET,POST
            - Path=/user/**

server:
  port: 45000
````
