### ISSUE TITLE
RetryLoadBalancerInterceptor does not allow to retry on specific exceptions

### ISSUE THREAD

**Issue by danparisi** [spring-cloud/spring-cloud-commons#1043]
**Is your feature request related to a problem? Please describe.**
I'd like to configure retries not by status code (as it's currently allowed), but by exceptions. 
For example I'd like the call to be retried in case of _HttpHostConnectException_ or _ConnectTimeoutException_, etc.

**Describe the solution you'd like**
I'd like to have a property that lets me configure the exception list (something similar is provided by Resilience4j), for example:
```
spring:
  cloud:
    loadbalancer:
      retry:
        retryableExceptions:
          - org.apache.http.conn.ConnectTimeoutException
          - java.net.ConnectException
          - java.net.UnknownHostException
```

**Describe alternatives you've considered**
Maybe I could wrap the call with some other library that allows this feature, like _spring-retry_ or _resilience4j_ but I guess it won't work properly because - for example - the last instance won't be filtered and such retry could hit the same (broken) one.
