### ISSUE TITLE
Weight-based LoadBalancer strategy

### ISSUE THREAD

**Issue by mario45211** [spring-cloud/spring-cloud-commons#1063]
Hi Team,

**Is your feature request related to a problem? Please describe.**
I want to load balance traffic between target service's instances using tag and corresponding weight, provided by the configuration. That feature would help me to freely redirect significant part of traffic to a group of instances while the rest to e.g. instances with new feature. The best example of such strategy of LB is blue-green deployment.

**Describe the solution you'd like**
```
spring:
  cloud:
    consul:
      discovery:
        server-list-query-tags: # probably not the best config key but it's only example 
          service-name:
            - tag: group-1
              weight: 80
            - tag: group-2
              weigth: 20 
```

**Additional context**
Example of such implemention in Consul splitting configuration:
```hcl
Kind = "service-splitter"
Name = "<service-name>"
Splits = [
  {
    Weight        = 10
    ServiceSubset = "blue"
  },
  {
    Weight        = 90
    ServiceSubset = "green"
  },
]

```
Please, let me know what you think about such feature.

Best regards
