### ISSUE TITLE
preferredNetworks Regular expression parsing error

### ISSUE THREAD

**Issue by crazytreeChen** [spring-cloud/spring-cloud-commons#1068]
Environment:

spring-cloud-commons: 3.0.3
OpenJdk： 11

When preferredNetworks are configured in a multi-network interface card environment, regular expression parsing is incorrect. Procedure  
```
spring:
  cloud:
    inetutils:
      preferred-networks:
        - 35.
        - 12.
````
org.springframework.cloud.commons.util.InetUtils#isPreferredAddress,Identify the content as a value.

I expected the regular expression to match 35.*.*.*, but I found it matched 35.0
