### ISSUE TITLE
Provide a mechanism to configure the weight of server, and a weighted-loadbalancing strategy 

### ISSUE THREAD

**Issue by jizhuozhi** [spring-cloud/spring-cloud-commons#1102]
**Is your feature request related to a problem? Please describe.**
I want to configure my application's weight and the client load balancer could use 
weighted-strategy to choose the ServiceInstance.

There is a common use case, we have three group ECS servers, having 1C4G, 2C4G and 4C4G 
(assuming they have the same number of machines). With the diferent number of CPU cores, 
the number of requests they can handle is different, so we would like to allocate 1/7 traffic to 
the 1C4G group, 2/7 traffic to the 2C4G group and 4/7 traffic to the 4C4G group.

**Describe the solution you'd like**
I can accept both configuration methods
1. using `spring.application.weight`
```yml
spring:
  application:
    name: application
    weight: 100
```
2. using `spring.cloud.{registry}.discovery.metadata.weight`
```yml
spring:
  cloud:
    consul:
      discovery:
        metadata:
          weight: 100
```
If not configured, using 100 by default.
And then, in the loadbalancer we provide a new loadbalancer named as `WeightedRoundRobinLoadBalancer` 
or just `WeightedLoadBalancer` using EDF scheduling algorithm.
