### ISSUE TITLE
WebClient Bean Configuration with considering `LoadBalancerExchangeFilterFunction` (Zone-aware)

### ISSUE THREAD

**Issue by kworkbee** [spring-cloud/spring-cloud-commons#1185]
I wonder if it is appropriate to write this post in the area, but please understand that I am writing it for help.

Assuming that there are two zones, you are configuring WebClient Bean with LoadBalancerExchangeFilterFunction to request the default zone first and connect to the secondary zone if inaccessible. How should the baseUrl in WebClient Builder be specified in this case?

If the relevant implementation does not exist, can you request to support the feature?
Thank you.

```yaml
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            a:
              - host: a.com
                port: 80
            b:
              - host: b.com
                port: 80
```

```java
@Bean
public WebClient webClient(LoadBalancerExchangeFilterFunction loadbalancerExchangeFilterFunction) {
  return WebClient.builder()
                  .filter(loadbalancerExchangeFilterFunction)
                  .baseUrl("http://[zone]/") // Zone A ? Zone B?
                  .build();
}
```
