### ISSUE TITLE
SameInstancePreferenceServiceInstanceListSupplier.selectedServiceInstance(...) not call  

### ISSUE THREAD

**Issue by Anton-Bondar** [spring-cloud/spring-cloud-commons#1252]
I use Spring Cloud Load Balancer 3.1.1. And I want to use same instance strategy for it.

```
spring:
  cloud:
    loadbalancer:
      configurations: same-instance-preference   
```

But each time even service calling not first time **SameInstancePreferenceServiceInstanceListSupplier.previouslyReturnedInstance == null** 
As I understood following method should set it: SameInstancePreferenceServiceInstanceListSupplier.selectedServiceInstance(...)
But it isn't call in my case. Please describe how it should works or maybe it's a bug?
