### ISSUE TITLE
Unable to override local configurations using -Dspring.profiles.active=pre on SpringCloud version 2021.0.8.

### ISSUE THREAD

**Issue by Iamdouding** [spring-cloud/spring-cloud-commons#1317]
spring-cloud-dependencies  version 2021.0.8.   

Problem Description：
I specified the Spring configuration in bootstrap.yml as follows:

```yaml
spring:
  profiles:
    active: dev
```    

 At the same time, I overrode it during startup using -Dspring.profiles.active=pre. However, when using the Spring Cloud Dependencies version 2021.0.8, the active profile is not overridden correctly. Instead, it outputs the following information: "The following 2 profiles are active: "pre", "dev".

springBoot version is 2.6.15

**Comment by ryanjbaxter** [comment]
Can you try Spring Cloud 2022.0.4 and see if there is the same behavior?

**Comment by Iamdouding** [comment]
I did not use the 2022.0.4 version, but trying with version 2021.0.7 worked. My solution was to change the configuration from:
```yaml
spring:
  profiles:
    active: dev
```    
to:
```yaml
spring:
  profiles:
    default: dev
```
