### ISSUE TITLE
If I use bootstrap.yml, I don't understand why it adopts properties that are mapped to the last defined value 'spring.config.activate.on-profile'.

### ISSUE THREAD

**Issue by kworkbee** [spring-cloud/spring-cloud-commons#1416]
**Describe the bug**
Boot 3.X / Cloud 2022.0.4 (or 2023.0.X) ~ 

If I use `bootstrap.yml`, I don't understand why it adopts properties that are mapped to the last defined value 'spring.config.activate.on-profile'.

When running the application, it doesn't seem to care what the 'spring.profiles.active' value has.

```yaml
spring:
  cloud:
    config:
      fail-fast: true
  profiles:
    active: local
  application:
    name: test
---
spring:
  config.activate.on-profile: prd
  cloud:
    config:
      uri: ***
      profile: prd,${hostname:hostname},prd-${hostname:hostname},tomcat,tomcat-prd,tomcat-prd-${hostname:hostname}
---
spring:
  config.activate.on-profile: prd,type1
  cloud:
    config:
      uri: ***
      profile: prd,${hostname:hostname},prd-${hostname:hostname},tomcat,tomcat-prd-type1,tomcat-prd-type1-${hostname:hostname}
---
spring:
  config.activate.on-profile: prd,type2
  cloud:
    config:
      uri: ***
      profile: prd,${hostname:hostname},prd-${hostname:hostname},tomcat,tomcat-prd-type2,tomcat-prd-type2-${hostname:hostname}
---
spring:
  config.activate.on-profile: prd,type3
  cloud:
    config:
      uri: ***
      profile: prd,${hostname:hostname},prd-${hostname:hostname},tomcat,tomcat-prd-type3,tomcat-prd-type3-${hostname:hostname}

```
