### ISSUE TITLE
Replace noop discovery client with one that is config driven

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-commons#180]
Possible config:
```
spring.cloud.discovery.client.simple:
  service1:
  - host1:8080
  - host2:8080
  service2:
  - host3:80
```

**Comment by spencergibb** [comment]
See #140

**Comment by bijukunjummen** [comment]
The PR is likely to be  rough and will require some level of polish based on your review comments. The props specified is a little different in the PR, than in the issue:

```
spring.cloud.discovery.client.simple.instances:
    service1: 
        - http://host1:8080
        - https://host2:8443
    service2:
        - http://host3:8080
        - http://host4:8080
```
