### ISSUE TITLE
Calling /restart endpoint does not cleanup the bootstrap ApplicationContext

### ISSUE THREAD

**Issue by arne-vandamme** [spring-cloud/spring-cloud-commons#333]
When activating the `/restart` endpoint and calling it, it appears that the parent bootstrap `ApplicationContext` does not get closed. Everytime restart is called, the `LiveBeansView` shows an extra `ApplicationContext`. It's also present in the actuator `/beans` endpoint.

It's the context called `bootstrap` that gets duplicated. When debugging it appears that `AbstractApplicationContext#doClose` is never called for that context.

### How to reproduce
Reproduced with Edgeware.SR2. 
start.spring.io project with Spring Boot Admin Server and Client with `/restart` enabled.

**DemoApplication**
```
@SpringBootApplication
@EnableAdminServer
public class DemoApplication {
    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}
```

**application.yml**
```
spring.boot.admin.url: http://localhost:8080
management.security.enabled: false

endpoints:
  restart:
    enabled: true
```

**curl request**
`curl -X POST http://localhost:8080/restart`
