### ISSUE TITLE
Document Enabling Refresh Endpoint In Finchley

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-commons#343]
```
management:
  endpoints:
    web:
      exposure:
        include: refresh
```
