### ISSUE TITLE
[Enhancement] Need extra knowledge to be able to refresh immutable beans

### ISSUE THREAD

**Issue by chengchen** [spring-cloud/spring-cloud-commons#363]
Hello,

We have recently upgrade to spring boot 2.0.1 along with spring clould Finchley.RC1. During the migrations, we noticed a pretty implicit issue while using customized data source configuration with spring cloud context refreshing. The application could fail with such exceptions: "Caused by: java.lang.IllegalStateException: The configuration of the pool is sealed once started.  Use HikariConfigMXBean for runtime changes."

Steps to reproduce:
1. Use spring boot 2.x with spring cloud Finchley.RC1, and spring-boot-starter-actuator to refresh the context
2. Define a customized data source like what's suggested in spring boot reference:

```java
@Configuration
public class DataSourceConfig {
    @Bean
    @ConfigurationProperties(prefix = "datasource.main", ignoreUnknownFields = false)
    DataSource dataSource() {
        return DataSourceBuilder.create().build();
    }
}
```

Plus the yml config:
```yaml
datasource:
  main:
    jdbc-url: jdbc:h2:mem:main # jdbc-url is required by Hikari which is the default CP now
    username: user
    password: pass
```

3. Activate the refresh endpoint:
```yaml
management:
  endpoints:
    web:
      exposure:
        include: refresh
```

4. Start the application and hit POST /actuator/refresh, and you will see the error above.

Potential solutions:
Since the Hikari data source is immutable and can be only changed via jmx, it will always fail if we rebind the new properties using the same object. The solution would be using "@RefreshScope" in org.springframework.cloud.context.config.annotation on the declared data source or any other immutable beans. However, this knowledge is hard to find at least from your documentation. It would be great to have it stated explicitly which could potentially save a lot of time.
