### ISSUE TITLE
The precedence of loading cipher in EnvironmentDecryptApplicationInitializer.decrypt is different as spring.profiles.active does

### ISSUE THREAD

**Issue by AndyLvVip** [spring-cloud/spring-cloud-commons#574]
Hello, 
Let's create a spring cloud project with two profiles: dev(application-dev.yml), dev-andy(application-dev-andy.yml)

main content of application-dev.yml
```
spring:
  datasource:
    username: dev-db-user
    password: "{cipher}dev-cipher"
```

main content of application-dev-andy.yml
```
spring:
  datasource:
    username: dev-andy-db-user
    password: "{cipher}dev-andy-cipher"
```

main content of bootstrap.yml
```
spring:
  profiles:
    active:
      - dev
      - dev-andy
```
Actual result: Got the user dev-andy-db-user with password dev-cipher
Expected result: Should got the dev-andy-db-user with password dev-andy-cipher

Spring Cloud Version: 'Greenwich.SR1' 
Spring Boot Version: '2.1.3.RELEASE'

I have found that EnvironmentDecryptApplicationInitializer.decrypt(PropertySource<?>, Map<String, Object>) will load the spring.datasource.password from application-dev-andy.yml firstly, and then override it by loading from application-dev.yml.
Seems that the precedence of loading configuration items in EnvironmentDecryptApplicationInitializer.decrypt is different as spring.profiles.active does?
Is there anybody can take a look? Thanks in advance.
