### ISSUE TITLE
Fetch secret property prefix with {vault} directely in Hashcorp vault

### ISSUE THREAD

**Issue by jpiccaluga** [spring-cloud/spring-cloud-commons#618]
Hello,

I would like to suggest a new feature to be able to fetch secret property prefixed by {vault} directly in Hashicorp vault.
For example, we can have this:
```
---
my-app:
  db:
    user: test
    password: '{vault}<secret engin path>#<secret key>
```
In my point of view, this is a better integration than using spring-cloud-config-server with the vault backend.

Indeed this pattern allows having a clear view of all properties in one place instead of having some properties in a git backend and some secret properties in a vault backend.

This pattern is also very convenient to integrate with the vault Kubernetes auth method.

I already implement this feature in my projects.
If you are interested I can publish a merge   ##request.

Best regards,

Julien Piccaluga
