### ISSUE TITLE
Add server list filters for loadbalancer

### ISSUE THREAD

**Issue by HashZhang** [spring-cloud/spring-cloud-commons#744]
Add server list filters for loadbalancer, just like the serverlistfilter in Ribbon

**Comment by HashZhang** [comment]
And the configuration is like:

```
spring:
  cloud:
    loadbalancer:
      your-service:
        filters: 'org.springframework.cloud.loadbalancer.filter.EurekaZoneAffinityServerInstanceFilter'
```
