### ISSUE TITLE
@RefreshScope not working with property placeholders

### ISSUE THREAD

**Issue by jmalone912** [spring-cloud/spring-cloud-commons#968]
Spring Cloud version 2020.0.1
Spring Boot version 2.4.5

When we hit the https://host/actuator/refresh endpoint with a "POST" request, the application uses the string literal e.g "${development.uri}" to attempt to refresh the configurations instead of filling the placeholder with the proper string like it does on app startup.

{"timestamp":"2021-05-14T14:42:33.255Z","message":"Could not locate PropertySource: Invalid URL: ${development.uri}","logger":"o.s.b.c.c.ConfigDataLoader","level":"WARN"}

During application startup:
{"timestamp":"2021-05-14T14:43:17.977Z","message":"Fetching config from server at : https://configserverhost.com/","logger":"o.s.b.c.c.ConfigDataLoader","level":"INFO"}

I confirmed that this is not an issue if the string is hardcoded.

our application.yml:

```
spring:
  profiles:
    active: local
  application:
    name: ${name?:unknown}
  cloud:
    config:
      enabled: true
  config:
    import:
      - optional:configserver:\${development.uri}
      - optional:configserver:\${integration.uri}
      - optional:configserver:\${volume.uri}
      - optional:configserver:\${production.uri}
```

I wasn't sure if this was an issue within spring-cloud or spring-boot, so apologies if it is posted in the wrong place.
